export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_SUCCESS =  'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL'; 
export const LOGOUT = 'LOGOUT';

// subjects
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS'
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL'
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS'
export const FETCH_SUBJECTS_FAIL = 'FETCH_SUBJECTS_FAIL'
export const EDITE_SUBJECT_SUCCESS = 'EDITE_SUBJECT_SUCCESS'
export const EDITE_SUBJECT_FAIL = 'EDITE_SUBJECT_FAIL'
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS'
export const DELETE_SUBJECT_FAIL = 'DELETE_SUBJECT_FAIL'

// topics
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS'
export const CREATE_TOPIC_FAIL = 'CREATE_TOPIC_FAIL'
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPIC_SUCCESS'
export const FETCH_TOPIC_FAIL = 'FETCH_TOPIC_FAIL'
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS'
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL'
export const EDITE_TOPIC_SUCCESS = 'EDITE_TOPIC_SUCCESS'
export const EDITE_TOPIC_FAIL = 'EDITE_TOPIC_FAIL'
export const ADD_TOPIC = 'ADD_TOPIC'
export const REMOVE_TOPIC_FROM_STATE = 'REMOVE_TOPIC_FROM_STATE'

export const FETCH_TOPIC_COUNT_SUCCESS = 'FETCH_TOPIC_COUNT_SUCCESS'
export const FETCH_TOPIC_COUNT_FAIL = 'FETCH_TOPIC_COUNT_FAIL'

//flashcards
export const CREATE_FLASHCARD_SUCCESS = 'CREATE_FLASHCARD_SUCCESS'
export const CREATE_FLASHCARD_FAIL = 'CREATE_FLASHCARD_FAIL'
export const FETCH_FLASHCARD_REQUEST = 'FTECH_FLASHCARD_REQUEST'
export const FETCH_FLASHCARD_SUCCESS = 'FTECH_FLASHCARD_SUCCESS'
export const FETCH_FLASHCARD_FAIL = 'FETCH_FLASHCARD_FAIL'
export const CREATE_FLASHCARD_STATE_SUCCESS = 'CREATE_FLASHCARD_STATE_SUCCESS'
export const CREATE_FLASHCARD_STATE_FAIL = 'CREATE_FLASHCARD_STATE_FAIL'
export const FETCH_FLASHCARD_COUNT_SUCCESS = 'FETCH_FLASHCARD_COUNT_SUCCESS'
export const FETCH_FLASHCARD_COUNT_FAIL = 'FETCH_FLASHCARD_COUNT_FAIL'
export const EXPLAIN_FLASHCARD_SUCCESS = 'EXPLAIN_FLASHCARD_SUCCESS'
export const EXPLAIN_FLASHCARD_FAIL = 'EXPLAIN_FLASHCARD_FAIL'
export const CLEAR_EXPLANATION = 'CLEAR_EXPLANATION'

export const FETCH_FLASHCARDS_COUNT_SUCCESS = 'FETCH_FLASHCARDS_COUNT_SUCCESS'
export const FETCH_FLASHCARDS_COUNT_FAIL = 'FETCH_FLASHCARDS_COUNT_FAIL'
//all the data
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL    = 'FETCH_DATA_SUCCESS'

// ai actions
export const CHAT_RESPONSE_REQUEST = 'CHAT_RESPONSE_REQUEST'
export const CHAT_RESPONSE_SUCCESS = 'CHAT_RESPONSE_SUCCESS'
export const CHAT_RESPONSE_FAIL = 'CHAT_RESPONSE_FAIL'

export const IMPORT_REQUEST = 'IMPORT_REQUEST'
export const IMPORT_SUCCESS = 'IMPORT_SUCCESS'
export const IMPORT_FAIL = 'IMPORT_FAIL'

export const FETCH_SECTIONS_SUCCESS = 'FTCH_SECTIONS_SUCCESS'
export const FETCH_SECTIONS_FAIL = 'FETCH_SECTIONS_FAIL'

export const UPDATE_SECTION_SUCCESS = 'UPDATE_SECTION_SUCCESS'
export const UPDATE_SECTION_FAIL = 'UPDATE_SECTION_FAIL'

export const CLEAR_CHAT_AI = 'CLEAR_CHAT_AI'

export const CLEAR_EXPLANATION_QUESTION = 'CLEAR_EXPLANATION_QUESTION'

export const CHECK_HARDFLASHCARDS_REQUEST = 'CHECK_HARDFLASHCARDS_REQUEST'
export const CHECK_HARDFLASHCARDS_SUCCESS = 'CHECK_HARDFLASHCARDS_SUCCESS'
export const CHECK_HARDFLASHCARDS_FAIL = 'CHECK_HARDFLASHCARDS_FAIL'

export const CHECK_HARDFLASHCARDS_AUDIO_REQUEST = 'CHECK_HARDFLASHCARDS_AUDIO_REQUEST'
export const CHECK_HARDFLASHCARDS_AUDIO_SUCCESS = 'CHECK_HARDFLASHCARDS_AUDIO_SUCCESS'
export const CHECK_HARDFLASHCARDS_AUDIO_FAIL = 'CHECK_HARDFLASHCARDS_AUDIO_FAIL'



// question
export const CREATE_QUESTIONS_REQUEST = 'CREATE_QUESTIONS_REQUEST'
export const CREATE_QUESTIONS_SUCCESS = 'CREATE_QUESTIONS_SUCCESS'
export const CREATE_QUESTIONS_FAIL = 'CREATE_QUESTIONS_FAIL' 

export const FETCH_QUESTIONS_REQUEST = 'FETCH_QUESTIONS_REQUEST' 
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS' 
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL' 

export const EXPLAIN_QUESTIONS_REQUEST = 'EXPLAIN_QUESTIONS_REQUEST'
export const EXPLAIN_QUESTIONS_SUCCESS = 'EXPLAIN_QUESTIONS_SUCCESS'
export const EXPLAIN_QUESTIONS_FAIL = 'EXPLAIN_QUESTIONS_FAIL' 

export const CREATE_FLASHCARD_AI_REQUEST = 'CREATE_FLASHCARD_AI_REQUEST'
export const CREATE_FLASHCARD_AI_FALI = 'CREATE_FLASHCARD_AI_FALI'
export const CREATE_FLASHCARD_AI_SUCCESS = 'CREATE_FLASHCARD_AI_SUCCESS'


// dashboard
export const FETCH_FLASHCARDS_DASHBOARD_SUCCESS = 'FETCH_FLASHCARDS_DASHBOARD_SUCCESS'
export const FETCH_FLASHCARDS_DASHBOARD_FAIL = 'FETCH_FLASHCARDS_DASHBOARD_FAIL'

export const FETCH_SECTIONS_STATUS_SUCCESS = 'FETCH_SECTIONS_STATUS_SUCCESS'
export const FETCH_SECTIONS_STATUS_FAIL = 'FETCH_SECTIONS_STATUS_FAIL'

export const FETCH_NUMBER_OF_REVIEW_SUCCESS = 'FETCH_NUMBER_OF_REVIEW_SUCCESS'
export const FETCH_NUMBER_OF_REVIEW_FAIL = 'FETCH_NUMBER_OF_REVIEW_FAIL'

export const FETCH_REQUEST_COST_SUCCESS = 'FETCH_REQUEST_COST_SUCCESS'
export const FETCH_REQUEST_COST_FAIL = 'FETCH_REQUEST_COST_FAIL'


export const FETCH_SUBTOPICS_SUCCESS = 'FETCH_SUBTOPICS_SUCCESS'
export const FETCH_SUBTOPICS_FAIL = 'FETCH_SUBTOPICS_FAIL'

export const FETCH_FLASHCARD_COUNT_DASHBOARD_SUCCESS = 'FETCH_FLASHCARD_COUNT_DASHBOARD_SUCCESS'
export const FETCH_FLASHCARD_COUNT_DASHBOARD_FAIL = 'FETCH_FLASHCARD_COUNT_DASHBOARD_FAIL'

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'

export const GENERATE_QUESTION_NEWCHAT_REQUEST = 'GENERATE_QUESTION_NEWCHAT_REQUEST'
export const GENERATE_QUESTION_NEWCHAT_SUCCESS = 'GENERATE_QUESTION_NEWCHAT_SUCCESS'
export const GENERATE_QUESTION_NEWCHAT_FAIL = 'GENERATE_QUESTION_NEWCHAT_FAIL'

export const GENERATE_FLASHCARD_NEWCHAT_REQUEST = 'GENERATE_FLASHCARD_NEWCHAT_REQUEST'
export const GENERATE_FLASHCARD_NEWCHAT_SUCCESS = 'GENERATE_FLASHCARD_NEWCHAT_SUCCESS'
export const GENERATE_FLASHCARD_NEWCHAT_FAIL = 'GENERATE_FLASHCARD_NEWCHAT_FAIL'

export const FETCH_ALL_FILES_REQUEST = 'FETCH_ALL_FILES_REQUEST'
export const FETCH_ALL_FILES_SUCCESS = 'FETCH_ALL_FILES_SUCCESS'
export const FETCH_ALL_FILES_FAIL = 'FETCH_ALL_FILES_FAIL'
